# Generated by Django 5.2.7 on 2025-10-23 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpreadsheetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='spreadsheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('total_columns', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('cubic', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('ncm', models.CharField(blank=True, max_length=50, null=True)),
                ('prices', models.JSONField(default=dict, help_text="Dicionário de preços, ex: {'Preço Fornecido': 123.45, 'Grupo 1': 150.00}")),
                ('raw_data', models.JSONField(default=dict, help_text='Dados brutos da linha da planilha')),
                ('row_number', models.IntegerField(help_text='Número da linha na planilha original')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='extractor.product')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='extractor.spreadsheetupload')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='extractor.spreadsheetupload'),
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_column', models.IntegerField(blank=True, help_text='Índice da coluna de código', null=True)),
                ('description_column', models.IntegerField(blank=True, help_text='Índice da coluna de descrição', null=True)),
                ('dimensions_column', models.IntegerField(blank=True, help_text='Índice da coluna de dimensões', null=True)),
                ('cubic_column', models.IntegerField(blank=True, help_text='Índice da coluna de cúbico', null=True)),
                ('weight_column', models.IntegerField(blank=True, help_text='Índice da coluna de peso', null=True)),
                ('ncm_column', models.IntegerField(blank=True, help_text='Índice da coluna de NCM', null=True)),
                ('price_columns', models.JSONField(default=list, help_text="Lista de objetos com índice e nome da coluna de preço, ex: [{'index': 8, 'name': 'Preço Fornecido'}]")),
                ('data_start_row', models.IntegerField(default=0, help_text='Linha onde começam os dados (baseado em 0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='column_mapping', to='extractor.spreadsheetupload')),
            ],
        ),
    ]
