# Generated by Django 5.2.7 on 2025-10-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columnmapping',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='spreadsheetupload',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
