# Generated by Django 5.2.7 on 2025-10-27 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_alter_columnmapping_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome do template (ex: 'Planilha Fornecedor A')", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrição do template', null=True)),
                ('code_column', models.IntegerField(blank=True, null=True)),
                ('description_column', models.IntegerField(blank=True, null=True)),
                ('dimensions_column', models.IntegerField(blank=True, null=True)),
                ('cubic_column', models.IntegerField(blank=True, null=True)),
                ('weight_column', models.IntegerField(blank=True, null=True)),
                ('ncm_column', models.IntegerField(blank=True, null=True)),
                ('price_columns', models.JSONField(default=list)),
                ('data_start_row', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='columnmapping',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template utilizado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.mappingtemplate'),
        ),
    ]
