# Generated by Django 5.2.7 on 2025-11-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0003_mappingtemplate_columnmapping_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnmapping',
            name='column_headers',
            field=models.JSONField(default=dict, help_text="Nomes originais dos headers, ex: {'code': 'REF', 'description': 'PRODUTO', 'price_0': 'VL_ATACADO'}"),
        ),
    ]
