# Generated by Django 5.2.7 on 2025-11-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0004_columnmapping_column_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnmapping',
            name='dynamic_fields',
            field=models.JSONField(default=list, help_text="Lista de todos os campos detectados: [{'index': 0, 'name': 'Código', 'type': 'code'}, {'index': 1, 'name': 'Cor', 'type': 'attribute'}]"),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='fields',
            field=models.JSONField(default=dict, help_text="Todos os campos da linha, ex: {'código': 'ABC123', 'cor': 'Vermelho', 'tamanho': 'M', 'preço_1': 100}"),
        ),
    ]
