# Generated by Django 5.2.7 on 2025-11-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0006_remove_fixed_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnmapping',
            name='sheet_index',
            field=models.IntegerField(default=0, help_text='Índice da aba/sheet da planilha (0 = primeira aba)'),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='dynamic_fields',
            field=models.JSONField(default=list, help_text='Lista de TODOS os campos detectados pela IA com índice, nome original, tipo e confiança'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='fields',
            field=models.JSONField(default=dict, help_text='TODOS os campos da linha com nomes originais da planilha'),
        ),
    ]
