# Generated by Django 5.2.7 on 2025-11-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0007_columnmapping_sheet_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, help_text='Código do produto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cubic',
            field=models.CharField(blank=True, help_text='Cubagem', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem do produto', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='ncm',
            field=models.CharField(blank=True, help_text='NCM', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='Peso', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheetupload',
            name='company_name',
            field=models.CharField(blank=True, help_text='Nome da empresa vinculada', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheetupload',
            name='processed',
            field=models.BooleanField(default=False, help_text='Indica se a planilha foi processada'),
        ),
        migrations.AddField(
            model_name='spreadsheetupload',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora do processamento', null=True),
        ),
    ]
